# Generated by Django 2.2.5 on 2021-03-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contraseña_var', models.CharField(max_length=128)),
                ('id_usuario_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Configuracion')),
            ],
        ),
    ]
