# Generated by Django 2.2.5 on 2021-03-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_var', models.CharField(max_length=128, unique=True)),
                ('comment_var', models.CharField(max_length=128)),
                ('likes_var', models.CharField(max_length=128)),
                ('caption_var', models.CharField(max_length=128)),
                ('foto_post_var', models.ImageField(upload_to='post')),
                ('id_usuario_var', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.Configuracion')),
            ],
        ),
    ]
